#!/bin/bash

# xfce4-terminal colorscheme switcher.
# Usage:
#   $ colo whi                    # all
#   $ colo white                  # are
#   $ colo white-on-black         # same
#
# If you want different colorschemes for each terminal instance, see shell.shA
#
# Based on: https://askubuntu.com/a/676452

# if no arg supplied, list available themes
if [ $# -eq 0 ]
then
        ls /usr/share/xfce4/terminal/colorschemes/*.theme
        exit
fi

# set colorscheme
THEME=$(ls /usr/share/xfce4/terminal/colorschemes/$1*.theme | head -n 1)

# check if colorscheme exists
if ! [[ -f "$THEME" ]]
then
    echo "No such colorscheme: $1"
    exit 1
fi

# if not set, use default config dir
# this is used for setting different color profiles in each terminal (see shell.sh)
if [[ -z "${XDG_CONFIG_HOME}" ]]
then
        XDG_CONFIG_HOME=~/.config
fi


# Switch color. Uncomment Font and Background, if swithing those are desired, too.
cd $XDG_CONFIG_HOME/xfce4/terminal
grep -v "Color" terminalrc > .terminalrc.tmp
#grep -v "Font" terminalrc > .terminalrc.tmp
#grep -v "Background" terminalrc > .terminalrc.tmp
grep "Color" $THEME >> .terminalrc.tmp
#grep "Font" $THEME >> .terminalrc.tmp
#grep "Background" $THEME >> .terminalrc.tmp
mv .terminalrc.tmp terminalrc
